### ISSUE TITLE
Spritebot Not Generating SVG Spite Sheet

### ISSUE THREAD

**Issue by rwyatt86** [thomasjbradley/spritebot#9]
Hey, 

I am trying to use this tool, which from tutorials looks amazing, but after loading my SVGs and then clicking on the "Save Sprite Sheet" button nothing happens. I was hoping you could help me figure out why that may be.

**Comment by thomasjbradley** [comment]
Sorry you're running into problems.

- Can you send me the SVGs that you're trying to turn into a sprite sheet? (I'd like to look and see if there's a specific bug that they're running into.)
- Are you using Windows or Mac?

**Comment by rwyatt86** [comment]
I am using a Mac. Attached is a zipped file of the SVGs. I'm exporting them from Sketch and I am wondering if that is the issue. I also have a Sketch plugin that optimizes the SVGs upon exporting. That may be causing the problem as well. 
[dx-icons.zip](https://github.com/thomasjbradley/spritebot/files/1506793/dx-icons.zip)

**Comment by rwyatt86** [comment]
Also thanks for the help on this. I really appreciate it.

**Comment by thomasjbradley** [comment]
I can completely recreate the problem. When I drag all the icons and press the save button, the dialogue opens, but then it doesn't create the actual file.

I'll look into it and get back to you.

**Comment by thomasjbradley** [comment]
Try this version out and tell me how it works for you:
https://keybase.pub/thomasjbradley/Spritebot-1.3.2.dmg

Spritebot wasn't properly handling situations where there were `<use>` statements inside the symbols themselves.

**Comment by rwyatt86** [comment]
Would there be any way you could email me that version? Or is the file too large? I'm setting behind some secure proxy settings. My email is russell.wyatt@capitalone.com

**Comment by thomasjbradley** [comment]
It's definitely too large; would putting it in Dropbox work?

**Comment by thomasjbradley** [comment]
I went ahead and published the new version. I'm confident it should fix the problem for you.
https://github.com/thomasjbradley/spritebot/releases/tag/v1.3.3

Let me know if you run into any other problems.

**Comment by rwyatt86** [comment]
My apologies for just getting back to you. It worked wonderfully. Took me a bit to get it on my machine because I had to do a work around the proxy to download, but once I did everything went off like a charm. I really appreciate the speedy turnaround.
